---
apiVersion: v1
kind: Namespace
metadata:
  name: elkstack

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config
  namespace: elkstack
data:
  elasticsearch.yml: |
    cluster.name: my-elastic-cluster
    network.host: "0.0.0.0"
    bootstrap.memory_lock: false
    discovery.zen.ping.unicast.hosts: elasticsearch-cluster
    discovery.zen.minimum_master_nodes: 1
    xpack.security.enabled: false
    xpack.monitoring.enabled: true
  ES_JAVA_OPTS: -Xms8g -Xmx8g

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: alicloud-nas-elasticsearch
mountOptions:
  - nolock,tcp,noresvport
  - vers=3
parameters:
  server: "xxx.cn-hangzhou.nas.aliyuncs.com:/elk/elasticsearch/"
  driver: flexvolume
provisioner: alicloud/nas
reclaimPolicy: Retain

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: enode
  namespace: elkstack
spec:
  serviceName: elasticsearch-cluster
  replicas: 2
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: es-cluster
  template:
    metadata:
      labels:
        app: es-cluster
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: init-sysctl
          image: busybox
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
      containers:
        - name: elasticsearch
          resources:
            requests:
              cpu: 4
              memory: 8Gi
            limits:
              cpu: 6
              memory: 10Gi
          securityContext:
            privileged: true
            runAsUser: 1000
            capabilities:
              add:
                - IPC_LOCK
                - SYS_RESOURCE
          image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
          imagePullPolicy: IfNotPresent
          env:
            - name: ES_JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: es-config
                  key: ES_JAVA_OPTS
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /_cluster/health?local=true
              port: 9200
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /_cluster/health?local=true
              port: 9200
          ports:
            - containerPort: 9200
              name: es-http
            - containerPort: 9300
              name: es-transport
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
            - name: es-logs
              mountPath: /usr/share/elasticsearch/logs
            - name: elasticsearch-config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
      volumes:
        - name: elasticsearch-config
          configMap:
            name: es-config
            items:
              - key: elasticsearch.yml
                path: elasticsearch.yml
  volumeClaimTemplates:
    - metadata:
        name: es-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: alicloud-nas-elasticsearch
        resources:
          requests:
            storage: 500Gi
    - metadata:
        name: es-logs
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: alicloud-nas-elasticsearch
        resources:
          requests:
            storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  namespace: elkstack
spec:
  selector:
    app: es-cluster
  ports:
    - name: http
      port: 9200
      targetPort: 9200
  sessionAffinity: None
  type: ClusterIP


---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-cluster
  namespace: elkstack
spec:
  clusterIP: None
  selector:
    app: es-cluster
  ports:
    - name: transport
      port: 9300